apiVersion: aggregation.coder.com/v1alpha1
kind: CoderTemplate
metadata:
  name: default.e2e-template
  namespace: coder
spec:
  organization: default
  displayName: "E2E Template"
  description: "Created by coder-k8s merge-queue e2e"
  files:
    main.tf: |
      terraform {
        required_version = ">= 1.0"
      }
      resource "null_resource" "example" {}
