apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth-delegator-binding.yaml
  - authentication-reader-binding.yaml
  - clusterrolebinding.yaml
  - role.yaml
  - serviceaccount.yaml
