apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.aggregation.coder.com
spec:
  group: aggregation.coder.com
  version: v1alpha1
  service:
    name: coder-k8s-apiserver
    namespace: coder-system
  groupPriorityMinimum: 1000
  versionPriority: 100
  insecureSkipTLSVerify: true
