apiVersion: apps/v1
kind: Deployment
metadata:
  name: coder-k8s-apiserver
  namespace: coder-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coder-k8s-apiserver
  template:
    metadata:
      labels:
        app: coder-k8s-apiserver
    spec:
      serviceAccountName: coder-k8s-apiserver
      containers:
        - name: apiserver
          image: ghcr.io/coder/coder-k8s:latest
          args: ["--app=aggregated-apiserver"]
          ports:
            - containerPort: 6443
              name: https
