apiVersion: coder.com/v1alpha1
kind: CoderWorkspaceProxy
metadata:
  name: coderworkspaceproxy-sample
  namespace: coder
spec:
  image: "ghcr.io/coder/coder:latest"
  primaryAccessURL: "https://coder.example.com"
  proxySessionTokenSecretRef:
    name: coderworkspaceproxy-token
    key: token
