apiVersion: coder.com/v1alpha1
kind: CoderControlPlane
metadata:
  name: codercontrolplane-sample
  namespace: default
spec:
  image: "ghcr.io/coder/coder:latest"
  # Optional Enterprise license upload:
  # licenseSecretRef:
  #   name: coder-license
  #   key: license
