apiVersion: coder.com/v1alpha1
kind: WorkspaceProxy
metadata:
  name: workspaceproxy-sample
  namespace: default
spec:
  image: "ghcr.io/coder/coder:latest"
  primaryAccessURL: "https://coder.example.com"
  proxySessionTokenSecretRef:
    name: workspaceproxy-token
    key: token
